version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: coupon-postgres
    environment:
      POSTGRES_DB: coupon_db
      POSTGRES_USER: coupon_user
      POSTGRES_PASSWORD: coupon_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coupon-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coupon-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coupon_db
      SPRING_DATASOURCE_USERNAME: coupon_user
      SPRING_DATASOURCE_PASSWORD: coupon_pass
    depends_on:
      - postgres
    networks:
      - coupon-network

volumes:
  postgres_data:

networks:
  coupon-network:
    driver: bridge