spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/coupon_db}
    username: ${SPRING_DATASOURCE_USERNAME:coupon_user}
    password: ${SPRING_DATASOURCE_PASSWORD:coupon_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        
logging:
  level:
    com.vincenzo.coupon: INFO
    org.springframework.web: INFO